name: Deploy to EC2
on:
  push:
    branches:
    - master  # Change this if you want to trigger on a different branch
  pull_request:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2LINUX }}" > /tmp/ec2_key.pem
          chmod 400 /tmp/ec2_key.pem
    
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client
  
      - name: Deploy to EC2
        run: |
          ping ec2-54-227-93-158.compute-1.amazonaws.com
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ec2-user@ec2-54-227-93-158.compute-1.amazonaws.com << 'EOF'
            git pull origin main
            ./deploy.sh  # Replace with your actual deployment commands
          EOF
        env:
          HOST: ec2-13-61-177-118.eu-north-1.compute.amazonaws.com
