name: Deploy to EC2
on:
  push:
    branches:
    - master  # Change this if you want to trigger on a different branch
  pull_request:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2 }}" > /tmp/ec2.pem
          chmod 400 /tmp/ec2.pem
    
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client
  
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ubuntu@ec2-52-66-253-113.ap-south-1.compute.amazonaws.com << 'EOF'
            git pull origin main
            ./deploy.sh  # Replace with your actual deployment commands
          EOF
        env:
          HOST: ubuntu@ec2-52-66-253-113.ap-south-1.compute.amazonaws.com
